### ISSUE TITLE
Full dataset availability

### ISSUE THREAD

**Issue by AmitSharma1127** [LinWeizheDragon/AutoFidgetDetection#2]
Is the whole dataset available to download? I can see the demo video link in the main readme.md. If there's any portal where we need to register, please let me know about that.

**Comment by LinWeizheDragon** [comment]
Hi,

Currently, the fidgeting dataset with performed fidgets is publicly available. The dataset is from:
M. Mahmoud, L.-P. Morency, and P. Robinson, “Automatic multi-modal descriptors of rhythmic body movement,” in International Conference on Multimodal Interaction (ICMI).
Please contact M. Mahmoud for the download link.

The psychological distress dataset has, however, more limitation in privacy issue and participant agreement. We are still tackling with the publication, but you can still contact the corresponding author for more information. We now serve requests in a one-by-one manner.

Hope these help!

Best,
Weizhe
